from Exceptions.ExceptionCustom import ExceptionCustom


class NameNotFoundException(ExceptionCustom):
    pass